// Turn a supplied list (CSV or Excel) of halal restaurants / hotels / masjids /
// musafir khanas into import.sql for D1. Every row lands as PENDING and needs a
// moderator's approval in /moderate before it appears on the site.
//
// Usage:
//   npm run import:listings -- <file.csv|file.xlsx> [more files] [--kind restaurant] [--source "KGN list"]
//                              [--cities <directory.json URL or file>]
//   npx wrangler d1 execute jamaat_directory --remote --file=import.sql
//
// Only the FIRST sheet of an Excel file is read. City names are matched against
// the live directory (names + aliases, default: the deployed /directory.json) so
// "Poona" attaches to Pune; unmatched cities are created as pending.
//
// Column names are matched loosely (see src/lib/listings.ts and
// data/README.md). Re-running with the same list is safe: existing rows and
// cities are left untouched (INSERT OR IGNORE).

import { readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as XLSX from 'xlsx';
import { buildListingRows, type KnownCity, type RawRecord } from '../src/lib/listings.ts';
import type { CityRow, FacilityKind, FacilityRow } from '../src/lib/types.ts';
import { insert, type Row } from './sql.ts';

const KINDS: FacilityKind[] = ['masjid', 'musafir_khana', 'hotel', 'restaurant'];
const DEFAULT_CITIES = 'https://jamaat-directory.pages.dev/directory.json';

function parseArgs(argv: string[]) {
  const files: string[] = [];
  let kind: FacilityKind | undefined;
  let source: string | undefined;
  let citiesFrom = DEFAULT_CITIES;
  let out = resolve(dirname(fileURLToPath(import.meta.url)), '..', 'import.sql');
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--kind') {
      const k = argv[++i] as FacilityKind;
      if (!KINDS.includes(k)) throw new Error(`--kind must be one of ${KINDS.join(', ')}`);
      kind = k;
    } else if (a === '--source') source = argv[++i];
    else if (a === '--out') out = resolve(argv[++i]);
    else if (a === '--cities') citiesFrom = argv[++i];
    else files.push(a);
  }
  if (files.length === 0) throw new Error('give at least one .csv or .xlsx file');
  return { files, kind, source, out, citiesFrom };
}

function readRecords(file: string): RawRecord[] {
  // raw: true keeps CSV cells as typed text (no "09820…" -> 9820… number coercion).
  const wb = XLSX.read(readFileSync(file), { type: 'buffer', raw: true });
  return XLSX.utils.sheet_to_json<RawRecord>(wb.Sheets[wb.SheetNames[0]], { defval: '', raw: false });
}

async function loadKnownCities(from: string): Promise<KnownCity[]> {
  try {
    const text = /^https?:/.test(from)
      ? await (await fetch(from)).text()
      : readFileSync(from, 'utf8');
    const snap = JSON.parse(text) as { cities?: KnownCity[] };
    return snap.cities ?? [];
  } catch (e) {
    console.warn(`Could not load existing cities from ${from} (${(e as Error).message}).`);
    console.warn('Continuing: every city in the list will be treated as new. Pass --cities <file> to fix.');
    return [];
  }
}

const cityCols: Array<keyof CityRow> = [
  'id', 'name', 'jamaat_name', 'state', 'aliases', 'region',
  'nearest_rail', 'nearest_air', 'notes', 'office_phone', 'status', 'updated_at',
];
const facilityCols: Array<keyof FacilityRow> = [
  'id', 'city_id', 'kind', 'name', 'address', 'maps_url', 'phone', 'timings',
  'charges_band', 'booking_note', 'facilities', 'source', 'status', 'verified_at', 'created_at',
];

const args = parseArgs(process.argv.slice(2));
const knownCities = await loadKnownCities(args.citiesFrom);
console.log(`Matching against ${knownCities.length} existing cities.`);
const allCities = new Map<string, CityRow>();
const allFacilities = new Map<string, FacilityRow>();
let problems = 0;

for (const file of args.files) {
  const result = buildListingRows(readRecords(file), {
    defaultKind: args.kind,
    source: args.source ?? basename(file),
    knownCities,
  });
  for (const c of result.cities) if (!allCities.has(c.id)) allCities.set(c.id, c);
  for (const f of result.facilities) if (!allFacilities.has(f.id)) allFacilities.set(f.id, f);

  console.log(`\n${basename(file)}: ${result.facilities.length} listings, ${result.cities.length} new cities` +
    (result.duplicates ? `, ${result.duplicates} duplicate rows skipped` : ''));
  for (const e of result.errors) console.log(`  SKIPPED row ${e.row + 1}: ${e.message}`);
  for (const w of result.warnings) console.log(`  check   row ${w.row + 1}: ${w.message}`);
  problems += result.errors.length;
}

const sql = [
  `-- GENERATED by scripts/import-listings.ts from: ${args.files.map((f) => basename(f)).join(', ')}`,
  '-- Every row is PENDING. Existing cities/listings are never overwritten (INSERT OR IGNORE).',
  '',
  '-- cities (new ones only)',
  insert('cities', cityCols as string[], [...allCities.values()] as unknown as Row[], 'INSERT OR IGNORE'),
  '',
  '-- listings',
  insert('facilities', facilityCols as string[], [...allFacilities.values()] as unknown as Row[], 'INSERT OR IGNORE'),
  '',
].join('\n');

writeFileSync(args.out, sql, 'utf8');
console.log(`\nWrote ${args.out}: ${allFacilities.size} listings, ${allCities.size} new cities` +
  (problems ? ` (${problems} rows skipped — see above)` : '') + '.');
console.log('Load it with:  npx wrangler d1 execute jamaat_directory --remote --file=import.sql');
console.log('Then approve in /moderate. Nothing is public until approved.');
